---
name: 'Tag repository using semantic versioning based on the commit message'
description: |
  This action tags the repository using semantic
  versioning based on the commit message.
author: martoc
runs:
  using: 'composite'
  steps:
    - name: Tag repository
      shell: bash
      run: |
        TAG_VERSION=$(docker run -v $PWD:/workdir martoc/semver:1.0.0 calculate --path /workdir)
        TAG_NAME="v$TAG_VERSION"
        TAG_SHA=$(git rev-parse HEAD)

        echo "TAG_VERSION=$TAG_VERSION"
        echo "TAG_NAME=$TAG_NAME"
        echo "TAG_SHA=$TAG_SHA"
        echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
        echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
        echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_ENV"

        echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_OUTPUT"
        echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"
        echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_OUTPUT"

        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag $TAG_NAME
        git push --tags
