---
name: 'Tag repository using semantic versioning based on the commit message'
description: |
  This action tags the repository using semantic
  versioning based on the commit message.
author: martoc
runs:
  using: 'composite'
  steps:
    - name: Tag repository
      shell: bash
      run: |
        TAG_SHA=$(git rev-parse HEAD)
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "Skipping tag creation for pull requests"
          TAG_VERSION=${TAG_SHA:0:7}
          TAG_FLOATING_VERSION_MAJOR=$TAG_VERSION
          TAG_FLOATING_VERSION_MINOR=$TAG_VERSION
          TAG_NAME="$TAG_VERSION"
          TAG_FLOATING_MAJOR_NAME="$TAG_VERSION"
          TAG_FLOATING_MINOR_NAME="$TAG_VERSION"
        else
          OUTPUT=$(docker run -w /workdir -v $PWD:/workdir martoc/semver:1.2.0 calculate --path /workdir --add-floating-tags)
          TAG_VERSION=$(echo $OUTPUT | jq -r '.next_version')
          TAG_FLOATING_VERSION_MAJOR=$(echo $OUTPUT | jq -r '.floating_version_major')
          TAG_FLOATING_VERSION_MINOR=$(echo $OUTPUT | jq -r '.floating_version_minor')
          TAG_NAME="v$TAG_VERSION"
          TAG_FLOATING_MAJOR_NAME="v$TAG_FLOATING_VERSION_MAJOR"
          TAG_FLOATING_MINOR_NAME="v$TAG_FLOATING_VERSION_MINOR"

          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --tags --force
        fi

        echo "TAG_VERSION=$TAG_VERSION"
        echo "TAG_FLOATING_VERSION_MAJOR=$TAG_FLOATING_VERSION_MAJOR"
        echo "TAG_FLOATING_VERSION_MINOR=$TAG_FLOATING_VERSION_MINOR"
        echo "TAG_NAME=$TAG_NAME"
        echo "TAG_FLOATING_MAJOR_NAME=$TAG_FLOATING_MAJOR_NAME"
        echo "TAG_FLOATING_MINOR_NAME=$TAG_FLOATING_MINOR_NAME"
        echo "TAG_SHA=$TAG_SHA"

        echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
        echo "TAG_FLOATING_VERSION_MAJOR=$TAG_FLOATING_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "TAG_FLOATING_VERSION_MINOR=$TAG_FLOATING_VERSION_MINOR" >> "$GITHUB_ENV"
        echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
        echo "TAG_FLOATING_MAJOR_NAME=$TAG_FLOATING_MAJOR_NAME" >> "$GITHUB_ENV"
        echo "TAG_FLOATING_MINOR_NAME=$TAG_FLOATING_MINOR_NAME" >> "$GITHUB_ENV"
        echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_ENV"

        echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_OUTPUT"
        echo "TAG_FLOATING_VERSION_MAJOR=$TAG_FLOATING_VERSION_MAJOR" >> "$GITHUB_OUTPUT"
        echo "TAG_FLOATING_VERSION_MINOR=$TAG_FLOATING_VERSION_MINOR" >> "$GITHUB_OUTPUT"
        echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_OUTPUT"
        echo "TAG_FLOATING_MAJOR_NAME=$TAG_FLOATING_MAJOR_NAME" >> "$GITHUB_OUTPUT"
        echo "TAG_FLOATING_MINOR_NAME=$TAG_FLOATING_MINOR_NAME" >> "$GITHUB_OUTPUT"
        echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_OUTPUT"

