---
name: 'Tag repository using semantic versioning based on the commit message'
description: |
  This action tags the repository using semantic
  versioning based on the commit message.
author: martoc
runs:
  using: 'composite'
  steps:
    - name: Tag repository
      shell: bash
      run: |
        GITHUB_REPOSITORY=${{ github.repository }}

        mkdir -p .cdf || true
        curl -L \
            -H "Accept: application/octet-stream" \
            -H "Authorization: token $PERSONAL_GITHUB_TOKEN" \
            -o .cdf/semver \
            https://api.github.com/repos/martoc/semver/releases/assets/150737147
        chmod 755 .cdf/semver

        TAG_VERSION=$(.cdf/semver calculate --path $PWD)
        TAG_NAME="v$TAG_VERSION"
        TAG_SHA=$(git rev-parse HEAD)

        echo "TAG_VERSION=$TAG_VERSION"
        echo "TAG_NAME=$TAG_NAME"
        echo "TAG_SHA=$TAG_SHA"
        echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
        echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
        echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_ENV"

        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag $TAG_NAME
        git push --tags
