---
name: Build & Release

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  release:
    permissions:
      contents: write
    uses: martoc/workflow-github-actions/.github/workflows/publish.yml@5eb7821ce4e92cf10075d74bb33fcdd85e853063
    secrets: inherit
